import { parentPort, workerData } from 'node:worker_threads';
import pg from 'pg';
pg.types.setTypeParser(20, (value) => {
  const n = Number(value);
  if (!Number.isSafeInteger(n)) throw new Error('PostgreSQL integer exceeds safe JavaScript range');
  return n;
});
const client = new pg.Client({
  connectionString: workerData.url,
  connectionTimeoutMillis: 10000,
  statement_timeout: 20000,
});
let connectionError;
const ready = client.connect().catch((error) => {
  connectionError = error;
});
client.on('error', (error) => {
  connectionError = error;
});

// Transform only SQL code, preserving string literals and quoted identifiers.
function mapCode(sql, transform) {
  return sql
    .split(/('(?:''|[^'])*'|"(?:""|[^"])*")/g)
    .map((part, i) => (i % 2 ? part : transform(part)))
    .join('');
}
function statements(sql) {
  const chunks = [];
  let current = '';
  for (const part of sql.split(/('(?:''|[^'])*'|"(?:""|[^"])*")/g)) {
    if (part.startsWith("'") || part.startsWith('"')) {
      current += part;
      continue;
    }
    const split = part.split(';');
    current += split.shift();
    for (const tail of split) {
      if (current.trim()) chunks.push(current.trim());
      current = tail;
    }
  }
  if (current.trim()) chunks.push(current.trim());
  return chunks;
}
const quote = (name) => '"' + name.replaceAll('"', '""') + '"';
async function columns(table) {
  return (
    await client.query(
      `SELECT column_name AS name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=$1 ORDER BY ordinal_position`,
      [table],
    )
  ).rows.filter((r) => r.name !== 'rowid');
}
async function compat(sql, args = []) {
  sql = sql.trim().replace(/;$/, '');
  const pragma = sql.match(/^PRAGMA\s+table_info\((\w+)\)$/i);
  if (pragma)
    return {
      rows: (await columns(pragma[1])).map((c, cid) => ({ cid, name: c.name })),
      rowCount: 0,
    };
  if (/^PRAGMA\s+database_list/i.test(sql))
    return { rows: [{ seq: 0, name: 'main', file: 'postgresql' }], rowCount: 0 };
  if (/^PRAGMA/i.test(sql)) return { rows: [], rowCount: 0 };
  sql = sql.replace(
    /sqlite_master/gi,
    `(SELECT table_name AS name,'table' AS type FROM information_schema.tables WHERE table_schema=current_schema()) AS sqlite_master`,
  );
  if (/^CREATE TABLE/i.test(sql))
    sql = sql.replace(/\)\s*$/, ', rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE)');
  sql = sql.replace(/^(ALTER TABLE\s+\w+\s+ADD COLUMN)\s+(?!IF NOT EXISTS)/i, '$1 IF NOT EXISTS ');
  const insert = sql.match(/^INSERT(?: OR (IGNORE|REPLACE))? INTO\s+(\w+)\s*(?=VALUES|\()/i);
  if (insert) {
    const [, mode, table] = insert;
    sql = sql.replace(/^INSERT OR (IGNORE|REPLACE)/i, 'INSERT');
    if (new RegExp('^INSERT INTO\\s+' + table + '\\s+VALUES', 'i').test(sql)) {
      const names = (await columns(table)).map((c) => quote(c.name)).join(',');
      sql = sql.replace(/\bVALUES/i, '(' + names + ') VALUES');
    }
    if (mode === 'IGNORE') sql += ' ON CONFLICT DO NOTHING';
    if (mode === 'REPLACE') {
      if (table !== 'settings') throw new Error('Unsupported SQLite REPLACE table: ' + table);
      sql += ' ON CONFLICT(key) DO UPDATE SET value=excluded.value';
    }
  }
  let parameter = 0;
  sql = mapCode(sql, (part) =>
    part
      .replace(/\?/g, () => '$' + ++parameter)
      .replace(
        /\bAS\s+([a-z_][a-zA-Z0-9_]*[A-Z][a-zA-Z0-9_]*)\b/g,
        (_, alias) => 'AS ' + quote(alias),
      ),
  );
  const result = await client.query(sql, args);
  return { rows: result.rows || [], rowCount: result.rowCount || 0 };
}
parentPort.on('message', async ({ memory, type, sql, args }) => {
  const control = new Int32Array(memory, 0, 2);
  let output;
  try {
    await ready;
    if (connectionError) throw connectionError;
    if (type === 'ready') output = {};
    else if (type === 'close') {
      await client.end();
      output = {};
    } else if (type === 'native') {
      const r = await client.query(sql, args);
      output = { rows: r.rows, rowCount: r.rowCount };
    } else if (type === 'exec') {
      // Serialize bootstrap DDL across application processes. Release even on failure.
      const ddl = /^\s*(?:PRAGMA|CREATE|ALTER)/i.test(sql);
      if (ddl) await client.query('SELECT pg_advisory_lock(714936201)');
      try {
        for (const statement of statements(sql)) await compat(statement);
        output = {};
      } finally {
        if (ddl) await client.query('SELECT pg_advisory_unlock(714936201)');
      }
    } else output = await compat(sql, args);
  } catch (error) {
    output = { error: { message: error.message, code: error.code } };
  }
  let bytes = Buffer.from(JSON.stringify(output));
  if (bytes.length > memory.byteLength - 8)
    bytes = Buffer.from(
      JSON.stringify({ error: { message: 'PostgreSQL result exceeds 32 MB; use pagination' } }),
    );
  new Uint8Array(memory, 8, bytes.length).set(bytes);
  Atomics.store(control, 1, bytes.length);
  Atomics.store(control, 0, 1);
  Atomics.notify(control, 0);
});
